# Библиотеки

In [1]:
import numpy as np
import pandas as pd
from itertools import *
from more_itertools import *
from sympy import *
from scipy.special import *
import math
from fractions import Fraction
from scipy.stats import *
from tqdm.notebook import tqdm

# 1

Независимые случайные величины $X, Y, X, U, V, W$ имеют дисперсию, равную $1$. Найдите $\rho_{S,T}$ – коэффициент корреляции случайных величин $S =
3X + 3Y + 2Z + U + V + W$ и $T = 9X + 3Y + 2Z + 2U + V + W$

## Аналитика

Найдем ковариацию случайных величин $S$ и $T$:
\begin{align*}
\text{cov}(S,T) &= \text{cov}(3X + 3Y + 2Z + U + V + W, 9X + 3Y + 2Z + 2U + V + W) \\
&= 3\text{cov}(X,9X) + 3\text{cov}(Y,3Y) + 2\text{cov}(Z,2Z) + \text{cov}(U,2U) + \text{cov}(V,V) + \text{cov}(W,W) \\
&= 27\text{var}(X) + 9\text{var}(Y) + 4\text{var}(Z) + 2\text{var}(U) + \text{var}(V) + \text{var}(W) \\
&= 27 + 9 + 4 + 2 + 1 + 1 \\
&= 44
\end{align*}

Теперь найдем дисперсии случайных величин $S$ и $T$:
\begin{align*}
\text{var}(S) &= 3^2\text{var}(X) + 3^2\text{var}(Y) + 2^2\text{var}(Z) + \text{var}(U) + \text{var}(V) + \text{var}(W) \\
&= 9 + 9 + 4 + 1 + 1 + 1 \\
&= 25 \\
\text{var}(T) &= 9^2\text{var}(X) + 3^2\text{var}(Y) + 2^2\text{var}(Z) + 2^2\text{var}(U) + \text{var}(V) + \text{var}(W) \\
&= 81 + 9 + 4 + 4 + 1 + 1 \\
&= 100
\end{align*}

Теперь найдем коэффициент корреляции $\rho_{S,T}$:
\begin{align*}
\rho_{S,T} &= \frac{\text{cov}(S,T)}{\sqrt{\text{var}(S)\text{var}(T)}} \\
&= \frac{44}{\sqrt{25\cdot 100}} \\
&= \frac{44}{50} \\
&= 0.88
\end{align*}

Итак, $\rho_{S,T} = 0.88$.

## Кодом

## Нормальное распределение

$\sigma^2 = \frac{\Gamma(\frac{k+1}{2})}{\sqrt{\pi k} \Gamma(\frac{k}{2})}\\$
$\Gamma = \int_0^{+\infty} t^{x-1} \cdot e^{-t} \,dx$ , $k$ — количество наблюдений.

In [20]:
random_numbers = norm.rvs(size=100_000)
variance = np.var(random_numbers)
print(f"Дисперсия полученного распределения: {variance}")

Дисперсия полученного распределения: 1.0016885710987946


In [7]:
N = 1_000_000
rn = [norm() for _ in range(6)]
n = [X_i.rvs(N) for X_i in rn]
S = 3 * n[0] + 3 * n[1] + 2 * n[2] + n[3] + n[4] + n[5]
T = 9 * n[0] + 3 * n[1] + 2 * n[2] + 2 * n[3] + n[4] + n[5]
np.corrcoef(S, T)

array([[1.        , 0.88007036],
       [0.88007036, 1.        ]])

# 2

Дисперсии независимых случайных величин $U, V$ равны $1$. Для случайных величин $X = U + V$, $Y = 7U + V$, $Z = 7U − V$ найдите: 
а) корреляционную матрицу;   
б) определитель корреляционной матрицы.

## Аналитика

$$
R = 
\begin{pmatrix}
1 & \rho(X, Y) & \rho(X, Z) \\
\rho(Y, X) & 1 & \rho(Y, Z) \\
\rho(Z, X) & \rho(Z, Y) & 1 \\
\end{pmatrix}
$$

$$\rho(X, Y) = \frac{cov(X, Y)}{\delta(X) \delta(Y)} = \frac{8}{\sqrt{100}} = 0.8\\$$
$cov(X, Y) = cov(U + V, 7U+V) = cov(U, 7U+V) + cov(V, 7U+V) = cov(7U+V, U) + cov(7U+V, V) = cov(7U, U) + cov(V, U) + cov(7U, V) + cov(V, V) = 7Var(U) + Var(V) = 8 \\$
$\delta(X) = \sqrt{Var(U + V)} = \sqrt{Var(U) + Var(V) + cov(U, V)} = \sqrt{Var(U) + Var(V)} = \sqrt{2}\\$
$\delta(Y) = \sqrt{Var(7U + V)} = \sqrt{Var(7U) + Var(V) + 7cov(U,V)} = \sqrt{49Var(U)+Var(V)} = \sqrt{50}\\$

$$\rho(Y, Z) = \frac{cov(Y, Z)}{\delta(X) \delta(Y)} = \frac{48}{\sqrt{50} \sqrt{50}} = 0.96\\$$
$cov(Y, Z) = cov(7U + V, 7U - V) = 49Var(U) - Var(V) = 48\\$
$\delta(Y) = \sqrt{Var(7U + V)} = \sqrt{Var(7U) + Var(V) + 7cov(U,V)} = \sqrt{49Var(U)+Var(V)} = \sqrt{50}\\$
$\delta(Z) = \sqrt{Var(7U - V)} = \sqrt{(Var(7U) + Var(V) - cov(7U, -V))} = \sqrt{49Var(U)+Var(V)} = \sqrt{50}\\$

$$\rho(X, Z) = \frac{cov(X, Z)}{\delta(X) \delta(Z)} = \frac{6}{\sqrt{2}\sqrt{50}} = 0.6$$
$cov(X, Z) = cov(U + V, 7U - V) = 7Var(U) - Var(V) = 6\\$
$\delta(X) = \sqrt{Var(U + V)} = \sqrt{Var(U) + Var(V) + cov(U, V)} = \sqrt{Var(U) + Var(V)} = \sqrt{2}$
$\delta(Z) = \sqrt{Var(7U - V)} = \sqrt{(Var(7U) + Var(V) - cov(7U, -V))} = \sqrt{49Var(U)+Var(V)} = \sqrt{50}\\$

$$
R = 
\begin{pmatrix}
1 & 0.8 & 0.6 \\
0.8 & 1 & 0.96\\
0.6 & 0.96 & 1 \\
\end{pmatrix}
$$

$$det(A) = 0$$

In [9]:
A = np.matrix('1 0.8 0.6; 0.8 1 0.96; 0.6 0.96 1')
np.linalg.det(A)

-5.32907051820077e-17

## Кодом

In [8]:
N = 1_000_000
U = norm().rvs(N)
V = norm().rvs(N)
X = U + V
Y = 7 * U + V
Z = 7 * U - V

data = np.vstack([X, Y, Z])
correlation_matrix = np.corrcoef(data)

correlation_matrix, np.linalg.det(correlation_matrix)

(array([[1.        , 0.79970491, 0.59952142],
        [0.79970491, 1.        , 0.95997019],
        [0.59952142, 0.95997019, 1.        ]]),
 -1.600486299497035e-16)

# 3

Инвестор сформировал портфель $x$ из акций компаний $A$ и $B$, затратив
на приобретение акций $A$ в $10$ раз больше средств, чем на покупку акций
$B$. Ожидаемая доходность за период владения акциями $A$ и $B$ составляет $2\%$ и $5\%$, при этом стандартное отклонение доходности равно $3\%$ и $8\%$,
соответственно. Найдите (в $\%$) ожидаемую доходность $\mathbb E(R_x)$ и стандартное отклонение $\delta(R_x)$ доходности портфеля инвестора, если известно, что
коэффициент корреляции доходностей акций $A$ и $B$ равен $0,1$.

## Аналитика

Пусть $R_A, R_B$ - доходы с акций $A, B$ соответсвенно   
$\mathbb E_A = 0.02; \mathbb E_B = 0.05$  
$\delta = 0.03; \delta = 0.08$  
$\rho = \rho(R_A, R_B) = 0.1$  
$R_X = \alpha R_A + \beta R_B$. Значит $\alpha = \frac{10}{11}, \beta = \frac{10}{11}$  
$Var(R_X) = \alpha^2 \delta_A^2 + \beta^2 \delta_B^2 + 2 \alpha \beta \rho \delta_A \delta_B = \frac{23}{27500}$   
$\delta(R_X) = \frac{1}{50} \sqrt{\frac{23}{11}}$  
$\mathbb E(R_X) = \alpha E_A + \beta E_B = \frac{1}{44}$

# 4

Ожидаемая доходность и стандартное отклонение доходности за период
для акций компаний $A, B$ и $C$ составляют $2\%$, $2\%$, $3\%$ и $3\%$, $4\%$, $6\%$, соответственно. Предполагая независимость доходностей акций $A, B$ и $C$,
найдите (в $\%$) ожидаемую доходность $\mathbb (R_x)$ портфеля $x$, составленного из
этих акций так, чтобы дисперсия $Var(R_x)$ его доходности была минимальной. В ответе укажите также стоимостные доли $(в \%)$ акций $A, B$ и $C$ в
портфеле $x$.

## Аналитика

Пусть $R_A, R_B, R_C$ - доходность акций,  
$\mu(R_A) = 0.02, \mu(R_B) = 0.02, \mu(R_C) = 0.03$, $\mu(R) = \mathbb E(R)$  
$\delta_A = 0.03, \delta_B = 0.04, \delta_C = 0.06$  
Общая доходность: $R_{\pi} = \alpha R_A + \beta R_B + \gamma R_C$, где $\alpha, \beta, \gamma$ - сколько акций купим, Составим систему:  
$$
\begin{cases}
Var(R_\pi) \rightarrow min \\
\alpha + \beta + \gamma = 1
\end{cases}
$$

$\gamma = 1 - \alpha - \beta\\$

$Var(R_\pi) = Var(\alpha R_A + \beta R_B + \gamma R_C) = \alpha^2 Var(R_A) + \beta^2 Var(R_B) + (1-\alpha-\beta)^2 Var(R_C)$, тк события независимы  

$\langle \frac{\partial R_\pi}{\partial \alpha}; \frac{\partial R_\pi}{\partial \beta}; \rangle = 0 \Rightarrow \langle 2 \alpha Var(R_A) - 2(1-\alpha - \beta)Var(R_C); 2 \beta Var(R_B) - 2(1-\alpha - \beta)Var(R_C) \rangle = 0\\$

$$
\begin{cases}
2 \alpha \cdot 0.0009 - 2 (1 - \alpha - \beta) \cdot 0.0036 = 0 \\
2 \beta \cdot 0.0016 - 2 (1 - \alpha - \beta) \cdot 0.0036 = 0 \\
\end{cases}
\Rightarrow
\begin{cases}
\alpha = \frac{16}{29} \\
\beta = \frac{9}{29} \\
\gamma = \frac{4}{29}
\end{cases}
$$

$\mathbb E(R_\pi) = \mathbb E(\frac{16}{29} R_A + \frac{9}{29} R_B + \frac{4}{29} \gamma R_C) = \frac{16}{29} \cdot 0.02 + \frac{9}{29} \cdot 0.02 + \frac{4}{29} \cdot 0.03 \approx 0.021$

# 5
Пусть $R_1, R_2$ – доходности ценных бумаг двух видов, $\rho = \rho(R_1,R_2), \mu_i =
\mathbb E(R_i), \delta_i = \delta(R_i), i = 1,2$. Пусть $X$ – портфель, составленный из бумаг
данного вида. Найдите математическое ожидание портфеля $X$ с наименьшей дисперсией доходности, если $\mu_1 = 7\%, \delta_1 = 1\%, \mu_2 = 14\%, \delta_2 = 2\%,
\rho = −0,5$. Укажите также стандартное отклонение полученной доходности

## Аналитика

$X = \alpha R_1 + \beta R_2$, где $\alpha, \beta$ - сколько бумаг купили в долях   
$$
\begin{cases}
Var(X) \rightarrow min \\
\alpha + \beta = 1
\end{cases}
$$  
$\beta = 1 - \alpha$   
$Var(X) = Var(\alpha R_1 + (1 - \alpha) R_2) = \alpha^2 Var(R_1) + (1-\alpha)^2 Var(R_2) + cov(\alpha R_1, (1-\alpha) R_2) = ...$   
$cov(\alpha R_1, (1-\alpha) R_2) = \rho(\alpha R_1, (1-\alpha) R_2) \cdot \delta(\alpha R_1) \cdot \delta((1-\alpha) R_2) = -0.5 \alpha \cdot 0.01 \cdot (1 - \alpha) \cdot 0.02 = -0.0001 \alpha (1-\alpha)$  
$Var(X) = \alpha^2 \cdot 0.0001  + (1-\alpha)^2 \cdot 0.0004 - 0.0001 \alpha (1-\alpha)$  
$\frac{\,d Var(X)}{\,d \alpha}: 2 \alpha \cdot 0.0001 - 2 (1 - \alpha) \cdot 0.0004 - 0.0001 \cdot (1 - \alpha - \alpha) = 0 \Rightarrow \alpha = \frac{3}{4}$  

$\mathbb E(X) = \mathbb E(\frac{3}{4} R_1 + \frac{1}{4} R_2) = \frac{3}{4} \cdot 0.07 + \frac{1}{4} \cdot 0.14 = 0.0875$  

$\delta(X) = \sqrt{\alpha^2 \cdot 0.0001  + (1-\alpha)^2 \cdot 0.0004 - 0.0001 \alpha (1-\alpha)} \approx 0.009$  

# 6

## Аналитика
$$\mathbb E(X_n) = 1 \cdot \mathbb P(X_n = 1) + 0 \cdot \mathbb P(X_n = 0) = \frac{1}{n} \cdot 1 + (1 - \frac{1}{n}) \cdot 0 = \frac{1}{n}$$
$$VarX = \mathbb E(X^2) - \mathbb E^2(X)$$

Для нашей случайной величины $X_i$, имеющей два возможных значения 0 и 1, $\mathbb E(X\_i^2) = \mathbb P(X_i = 1) = \frac{1}{n}$, так как $X_i^2 = X_i$. Таким образом, дисперсия одного события равна:
$$Var(X_i) = \mathbb E(X_i^2) - \mathbb E^2(X_i) = \frac{1}{n} - (\frac{1}{n})^2 = \frac{1}{n} - \frac{1}{n^2}$$

Таким образом, общая дисперсия для $n$ событий будет:
$$Var(X_n) = n \cdot (\frac{1}{n} - \frac{1}{n^2}) = 1 - \frac{1}{n}$$

$$\lim_{n \rightarrow + \infty} Var(X_n) = \lim_{n \rightarrow + \infty} 1 - \frac{1}{n} = 1$$
$$\lim_{n \rightarrow + \infty} \mathbb E(X_n) = \sum_{i=1}^n \frac{1}{n} = 1$$

# 7

Корзина содержит $N$ пронумерованных шаров $1; 2; \ldots ; N$ . Из корзины без
возвращения извлекаются $n \leqslant N$ шаров. Пусть $S$ обозначает сумму номеров вынутых шаров. Найдите математическое ожидание $\mathbb E(S)$ и дисперсию $Var(S)$ этой суммы.

$$\mathbb{E}(S) = \sum_{i=1}^N \mathbb{E}(X_i) = \sum_{i=1}^N i = \frac{N(N + 1)}{2}.$$

Тк события _независимы_:
$$Var(S) = \sum_{i=1}^N Var(X_i)$$
Таким образом, дисперсия суммы будет равна сумме квадратов всех чисел минус квадрат суммы этих чисел:
$$Var(S) = \sum_{i=1}^N (i)^2 + \left(\sum_{i=1}^N i\right)^2 - \left(\sum_{i=1}^N i\right)^2.$$
Первая часть этого выражения представляет собой квадраты чисел от 1 до $N$, что также является суммой квадратов первых $N$ целых чисел:
$$\sum_{i=1}^N (i)^2 = \frac{N(N+1)(2N+1)}{6}.$$
Вторая часть выражения — это квадрат суммы первых $N$ целых чисел, который равен:
$$\left(\sum_{i=1}^N i\right)^2 = \left(\frac{N(N+1)}{2}\right)^2.$$
Теперь мы можем записать дисперсию $S$:
$$Var(S) = \frac{N(N+1)(2N+1)}{6} + \left(\frac{N(N+1)}{2}\right)^2 - \left(\frac{N(N+1)}{2}\right)^2.$$
Упрощая это выражение, получаем:
$$Var(S) = \frac{N(N+1)(2N+1)}{6} - \frac{(N(N+1)/2)^2}{4}.$$
Раскрыв скобки и упростив, получим:
$$Var(S) = \frac{N(N+1)(2N+1) - N^2(N+1)^2/4}{12} = \frac{3N^4 + 6N^3 + 2N^2 - N^4 - 2N^3 - N^2/4}{12} = \frac{2N^4 + 4N^3 + N^2/4}{12} = \frac{N^2(2N + 1)^2}{12}.$$

Правильный ответ: Математическое ожидание $\mathbb{E}(S) = \frac{N(N + 1)}{2}$, дисперсия $Var(S) = \frac{N^2(2N + 1)^2}{12}$.

# 9
Пусть $X_1, X_2, \ldots , X_n$ – случайные величины, коэффициент корреляции
любых двух из них равен $q \\$ Показать, что $ q \geqslant -\frac{1}{n-1}$

## Аналитика

$$Var(\sum_{i=1}^{n} X_i) = \sum_{i=1}^{n} Var(X_i) + 2 \sum_{1 \leqslant i < j \leqslant n} Cov(X_i, X_j)$$

$$Cov(X_i, X_j) = \rho(X_i, X_j) \sigma_{X_i} \sigma_{X_j} = q \sigma^2$$

$$Var(\sum_{i=1}^{n} X_i) \geqslant 0$$

$$\sum_{i=1}^{n} Var(X_i) + 2 \sum_{1 \leqslant i < j \leqslant n} Cov(X_i, X_j) \geqslant 0$$

$$n \sigma^2 + 2 q \sigma^2 \frac{n(n-1)}{2} \geqslant 0$$

$$n + q n (n-1) \geqslant$$

$$q \geqslant - \frac{1}{n-1}$$

# 10

Найти коэффициент корреляции между числом единиц и числом шестерок при $n$ бросаниях игрального кубика.

## Аналитика

Составим распределение случайной величины $X$:

|1|2|$\ldots$|n|
|:-:|:-:|:-:|:-:|
|$\frac{1}{6} \cdot \frac{5}{6} (n-1)$|$C_n^2 \frac{1}{6}^2 \frac{5}{6}^{n-2}$|$\ldots$|$\frac{1}{6}^n$| то

$\mathbb E(X) = \frac{n}{6}, Var(X) = n \frac{1}{6} \frac{5}{6}$

то распределение случайной величины $Y$ то же что и X, значит $\mathbb E(Y)$ и $Var(Y)$ совпадает с X

значит $\rho(X, Y) = 1$

In [18]:
val_1 = []
val_6 = []
X = rv_discrete(name="X", values=[list(range(1, 6+1)), [1/6 for _ in range(6)]])
for N in tqdm(range(10_000)):
    vals = X.rvs(size=10_000)
    val_1.append(vals[vals == 1].size)
    val_6.append(vals[vals == 6].size)


  0%|          | 0/10000 [00:00<?, ?it/s]

In [19]:
np.corrcoef(val_1, val_6)

array([[ 1.        , -0.20574364],
       [-0.20574364,  1.        ]])