# Библиотеки

In [1]:
import numpy as np
from scipy.stats import *

# 1

Найдите распределение случайной величины $Z = X + Y$ и $\mathbb E(Z)$, если известно распределение случайного дискретного вектора $(X, Y)$

||$X = 3$|$X = 4$|$X = 5$|
|:-:|:-:|:-:|:-:|
|$Y = -3$|$\frac{1}{6}$|$\frac{1}{24}$|$\frac{1}{6}$|
|$Y = -2$|$\frac{5}{24}$|$\frac{1}{12}$|$\frac{1}{3}$|

## Аналитика

$\mathbb E(Z) = \mathbb E(X + Y) = \mathbb E(X) + \mathbb E(Y)$  

||$X = 3$|$X = 4$|$X = 5$|
|:-:|:-:|:-:|:-:|
|$\mathbb P(X)$|$\frac{1}{6} + \frac{5}{24} = \frac{9}{24}$|$\frac{1}{24} + \frac{1}{12} = \frac{3}{24}$|$\frac{1}{6} + \frac{1}{3} = \frac{3}{6}$|

$\mathbb E(X) = 4,125$

||$Y = -3$|$Y = -2$|
|:-:|:-:|:-:|
|$\mathbb E(Y)$|$\frac{1}{6} + \frac{1}{24} + \frac{1}{6} = \frac{9}{24}$|$\frac{5}{24} + \frac{1}{12} + \frac{1}{3} = \frac{15}{24}$|

$\mathbb E(Y) = -2,375$  

$\mathbb E(Z) = 4,125 - 2,375 = 1,75$

## Стохастически

In [7]:
X = rv_discrete(name='X', values=[[3, 4, 5], [9/24, 3/24, 3/6]])
Y = rv_discrete(name='Y', values=[[-3, -2], [9/24, 15/24]])

In [8]:
N = 100_000
(X.rvs(size=N) + Y.rvs(size=N)).mean()

1.75167

# 2

Найдите распределение случайной величины $Z = min(6, X − Y)$ и $\mathbb E(Z)$,
если известно распределение дискретного случайного вектора $(X, Y)$

||$X = 3$|$X = 4$|$X = 5$|
|:-:|:-:|:-:|:-:|
|$Y = -2$|$\frac{1}{4}$|$\frac{1}{6}$|$\frac{1}{8}$|
|$Y = -1$|$\frac{1}{8}$|$\frac{1}{4}$|$\frac{1}{12}$|

## Аналитика



случаи, если $X - Y < 6$:  
$X = 3, Y = -2; X = 3, Y = -1; X = 4, Y = -1$  
Мат ожидание данного случая: $5 \cdot \frac{1}{4} + 4 \cdot \frac{1}{8} + 5 \cdot \frac{1}{4} = 3$

случаи, если $X - Y \geqslant 6$, то $Z = 6$:
$X = 4, Y = -2; X = 5, Y = -2; X = 5, Y = -1$
Мат ожидание данного случая: $6 \cdot (\frac{1}{6} + \frac{1}{8} + \frac{1}{12}) = 2,25$

То $\mathbb E(Z) = 3 + 2,25 = 5,25$

## Стохастический

In [6]:
N = 100_000
px = [1/4 + 1/8, 1/6 + 1/4, 1/8 + 1/12]
py = [1/4 + 1/6 + 1/8, 1/8 + 1/4 + 1/12]
X = rv_discrete(name="X", values=[[3, 4, 5], px])
Y = rv_discrete(name="Y", values=[[-2, -1], py])

In [8]:
np.fmin(X.rvs(size=N) - Y.rvs(size=N), [6] * N).mean()

5.25656

# 3

Для случайного дискретного вектора $(X, Y)$, распределенного по закону
||$X = -1$|$X = 0$|$X = 1$|
|:-:|:-:|:-:|:-:|
|$Y = -1$|$\frac{1}{28}$|$\frac{3}{14}$|$\frac{1}{28}$|
|$Y = 0$|$\frac{3}{14}$|$\frac{13}{28}$|$\frac{1}{28}$|

выясните, зависимы или нет события $A = \{X \cdot Y \neq 0\}$ и $B = \{X + Y = 0\}$.

## Аналитика

две случайные величины независимы, если:  
$Var(A + B) = Var(A) + Var(B)$
распределение величины $A$:  
|$X \cdot Y$|$-1$|$1$|$0$|
|:-:|:-:|:-:|:-:|
|$\mathbb P$|$\frac{1}{28}$|$\frac{1}{28}$|$\frac{26}{28}$|

$Var(A) = \frac{1}{28}$

распределение величины $B$:
|$X + Y$|$-2$|$-1$|$0$|$1$|
|:-:|:-:|:-:|:-:|:-:|
|$\mathbb P$|$\frac{1}{28}$|$\frac{6}{14}$|$\frac{14}{28}$|$\frac{1}{28}$|

$Var(B) = 0$

независимы

## Стохастически

In [4]:
N = 100_000

px = [1/28+3/14, 3/14+13/28, 1/28+1/28]
X = rv_discrete(name="X", values=[[-1, 0, 1], px])

py = [1/28+3/14+1/28, 3/14+13/28+1/28]
Y = rv_discrete(name="Y", values=[[-1, 0], py])

In [8]:
A = X.rvs(size=N) * Y.rvs(size=N)
A = A[A != 0]

B = X.rvs(size=N) * Y.rvs(size=N)
B = B[B == 0]

shorten = min(A.size, B.size)

(A[:shorten] + B[:shorten]).var(), A.var() + B.var()

(0.6873980084100131, 0.6873980084100131)

# 5

На отрезке $[0; 5]$ случайным независимым образом выбирается $n$ точек.
Пусть $X$ – число точек, попавших в промежуток $[0; 2]$, а $Y$ – число точек,
попавших в промежуток $[1; 4]$. Найдите коэффициент корреляции $\rho(X; Y )$.

## Аналитика

## Стохастически

In [28]:
A = uniform(loc=0, scale=5)

A_el = A.rvs(size=1_000_000)

X = A_el[A_el <= 2]
Y = A_el[(1 <= A_el) & (A_el <= 4)]

shorten = min(X.size, Y.size)

np.corrcoef(X[:shorten], Y[:shorten])

array([[1.       , 0.0013822],
       [0.0013822, 1.       ]])

# 6

Дискретная случайная величина $X$ принимает только целые значения $1; 2;
3; 4; 5$ и $6$, при этом вероятности $\{X = k\}$ пропорциональны принимаемым
значениям, т.е. $\mathbb P(X = k) = A \cdot k, k = 1, \dots , 6$. Пусть $Y_n$ – остаток от деления
$X$ на $n$ ($n$ = $2$ или $n$ = $3$). Найдите:
1) распределение $(Y_2; Y_3)$; 
2) Ковариационную и коррелляционную матрицы.

## Аналитика

$k = \frac{2}{7}$ 

## Стохастически

In [45]:
px = [i/6 * 2/7 for i in range(1, 6+1)]
X = rv_discrete(name="X", values=[list(range(1, 6+1)), px])

In [33]:
y2_vals = {0: [], 1: []}
for i in range(1, 6+1):
    y2_vals[i % 2].append(i)
y2_vals

{0: [2, 4, 6], 1: [1, 3, 5]}

In [38]:
Y2 = rv_discrete(name="Y2", values=[list(range(1, 6+1)), px[1::2] + px[::2]])

In [39]:
y3_vals = {0: [], 1: [], 2: []}
for i in range(1, 6+1):
    y3_vals[i % 3].append(i)
y3_vals

{0: [3, 6], 1: [1, 4], 2: [2, 5]}

In [42]:
Y3 = rv_discrete(name="Y3", values=[list(range(1, 6+1)), px[2::3] + px[::3] + px[1::3]])

In [51]:
np.cov(Y2.rvs(size=100_000), Y3.rvs(size=100_000))

array([[ 2.88305639, -0.00641706],
       [-0.00641706,  3.2953047 ]])

In [52]:
np.corrcoef(Y2.rvs(size=100_000), Y3.rvs(size=100_000))

array([[ 1.00000000e+00, -9.79811609e-04],
       [-9.79811609e-04,  1.00000000e+00]])