In [ ]:
# Версия Numpy
import numpy as np
np.__version__

'1.25.2'

In [ ]:
# Встроенная документация
np?

# Введение в массивы


#Создание массивов

In [ ]:
# Создание массива целочисленных значений из обычного списка:
data = [1, 4, 2, 5, 3]
np.array(data)
# или сразу
# np.array([1, 4, 5])

array([1, 4, 2, 5, 3])

In [ ]:
# В отличие от списков в Python, библиотека Numpy ограничивается массивами с элементами одного типа.
# В случае несовпадения типов переменных, numpy повышает приведение типов:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
# Задание типа данных явным образом:
np.array([1, 2, 3, 4], dtype='float32')
# или
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
# или
data = np.array([1, 2, 5], dtype=np.float)
print(data)
print(data.astype(np.int64))

In [ ]:
# Все доступные типы можно найти в словаре sctypes
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

In [ ]:
# Вложенные списки преобразуются в массив:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# Создание массива целых чисел длины 10, заполненного нулями:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Создание массива размером 3х5 значений с плавающей точкой, заполненного единицами:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Создание массива размером 3х5 заполненного значением 3.14:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# Создание массива из 5 значений, равномерно располагающихся между 0 и 1:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Создание массива, заполненного линейной последовательностью с 0 до 20, с шагом 2 (аналогично встроенной функции range),
# но отличие от питоновского range в том, что arange работает с дробными числами:
print(np.arange(0, 20, 2))
print(np.arange(2, 30.5, 1.6))

[ 0  2  4  6  8 10 12 14 16 18]
[ 2.   3.6  5.2  6.8  8.4 10.  11.6 13.2 14.8 16.4 18.  19.6 21.2 22.8
 24.4 26.  27.6 29.2]


In [ ]:
# Создание единичной матрицы размером 3х3:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Создание массивов из случайных значений**

In [ ]:
# Если мы хотим создать массив из 5 случайных чисел типа int в numpy в промежутке [0, 10)
data = np.random.randint(0, 10, 5)
data

array([6, 5, 1, 1, 5])

In [ ]:
# Создание массива размером 3х3 случайных числа int в промежутке [0, 10):
np.random.randint(0, 10, (3,3))

array([[4, 2, 0],
       [5, 5, 5],
       [8, 1, 8]])

In [ ]:
# Создание массива размером 3х3 равномерно распределенных случайных значений от 0 до 1
np.random.random((3,3))

array([[0.42392067, 0.20582377, 0.84690639],
       [0.50993544, 0.81595933, 0.46405701],
       [0.55588236, 0.58140888, 0.3710227 ]])

In [ ]:
# Создание массива размером 2х3 случайных чисел с нормальным распределением
np.random.randn(2,3)

array([[ 0.79582328, -0.12557266,  0.04888833],
       [-1.42205634,  0.73269595,  2.13099923]])

In [ ]:
# Создание массива размером 3х3 нормально распределенных случайных значений с медианой 0 и стандартным отклонением 1:
np.random.normal(0, 1, (3,3))

array([[ 0.19944536, -0.02088617,  1.87978981],
       [-0.03156301, -0.13150179,  0.55519253],
       [ 2.44547849, -0.58711398, -0.44875072]])

In [ ]:
# Случайные числа типа float
data = np.random.sample(5)
print(data)

data = np.random.sample((3,4))
print(data)

[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
[[0.0871293  0.0202184  0.83261985 0.77815675]
 [0.87001215 0.97861834 0.79915856 0.46147936]
 [0.78052918 0.11827443 0.63992102 0.14335329]]


In [ ]:
# Генератор случайных чисел с заданным начальным значением, чтобы гарантировать
# генерацию одних и тех же массивов при каждом выполнении
np.random.seed(0)

x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

print(x1)
print(x2)
print(x3)

# data = np.random.randn(2,3)
# print(data)

# data = np.random.randint(0, 10, (2,3))
# print(data)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


**Атрибуты numpy-массива**

In [ ]:
print('x3 ndim:', x3.ndim) # размерность
print('x3 shape:', x3.shape) # размер каждого измерения
print('x3 size:', x3.size) # общий размер массива
print('dtype:', x3.dtype) # тип данных массива
print('itemsize:', x3.itemsize, 'bytes') # выводит размер в байтах каждого элемента массива
print('nbytes:', x3.nbytes, 'bytes') # полный размер массива в байтах nbytes = itemsize * size

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


### Упражнения

1. Импортируйте библиотеку NumPy и выведите ее версию.
2. Создайте массив размерностью 3х3 из вложенного списка Python.
3. Создайте массив размером 5х5 случайных чисел int в промежутке [0, 15).
4. Создайте массив из 10 значений, равномерно располагающихся между 0 и 25.
5. Создайте массив размером 5х6 случайных чисел с нормальным распределением.
6. Создайте единичную матрицу, размером 5х5.
7. Создайте матрицу размерностью 4х5, заполненную нулями.
8. Создайте массив размерностью 5х5, заполненный числом 2.7.
9. Создайте массив из 7 случайных чисел типа int в numpy в промежутке [0, 15)
10. Заставьте массив из задания 9 при каждом новом выводе не менять значения элементов массива.


In [1]:
import numpy as np
np.__version__

'1.26.3'

In [2]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]] )

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.random.uniform(0, 15, (5, 5))

array([[13.65499662, 13.19340219,  3.02297534, 10.83807586,  4.11014071],
       [ 5.65199059,  1.73194024,  0.81595957,  1.23980543, 12.34309576],
       [ 5.98940611,  0.82327314, 10.64728918,  2.42103794,  6.34667869],
       [12.73417878,  5.55361592,  1.26147245, 12.91348013,  6.15850237],
       [ 6.75329366,  5.13023227, 14.40551786,  7.71364331, 12.65353533]])

In [11]:
np.linspace(0, 25, 10)

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [5]:
np.random.normal(size=(5, 5))

array([[ 0.22157644,  0.11277548,  1.44604459,  0.36525418, -1.08375314],
       [ 0.32032876,  1.17209122, -0.02568672, -0.318517  , -1.16382256],
       [ 1.0260254 , -0.42206878, -1.50917133,  0.62657258,  1.59324696],
       [ 1.12157296,  0.78716072,  2.93617922,  0.2085275 , -0.43538662],
       [-0.75395023,  0.2368963 , -0.33816648, -1.40903433,  0.6142229 ]])

In [6]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.full((5, 5), 2.7)

array([[2.7, 2.7, 2.7, 2.7, 2.7],
       [2.7, 2.7, 2.7, 2.7, 2.7],
       [2.7, 2.7, 2.7, 2.7, 2.7],
       [2.7, 2.7, 2.7, 2.7, 2.7],
       [2.7, 2.7, 2.7, 2.7, 2.7]])

In [9]:
np.random.randint(0, 15, 7)

array([ 1, 14, 11,  3,  2, 12,  0])

In [10]:
np.random.seed(42)

# Простые операции с массивами

**Индексация массива: доступ к отдельным элементам**

In [ ]:
print(x1)
print(x1[0])
print(x1[4])
print(x1[-1])

print(x2)
print(x2[0,0])
print(x2[2,0])

x2[0,0] = 12
print(x2)

# В отличие от списков языка Python , у массивов NumPy фиксированный тип данных, при вставке
# в массив числа с плавающей точкой, оно будет усечено:
x1[0] = 9.243
print(x1)

[5 0 3 3 7 9]
5
7
9
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
1
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[9 0 3 3 7 9]


**Срезы массивов, доступ к подмассивам**

1.Одномерные подмассивы

In [ ]:
# Срезы как в Python
x = np.arange(10)
print(x)
print(x[:5]) # первые 5 элементов
print(x[5:]) # после индекса = 5
print(x[4:7]) # подмассив из середины
print(x[::2]) # каждый второй элемент
print(x[1::2]) # каждый второй, начиная с индекса 1
print(x[::-1]) # в обратном порядке
print(x[5::-2]) # каждый второй в обратном порядке, начиная с индекса 5

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


2.Многомерные подмассивы

In [ ]:
# многомерные срезы создаются похожим образом, с разделением срезов запятыми
print(x2)
print(x2[:2, :3]) # две строки, три столбца
print(x2[:3, ::2]) # три строки, каждый второй столбец
print(x2[::-1, ::-1]) # измерения подмассивов также можно переворачивать

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5  2]
 [ 7  6  8]]
[[12  2]
 [ 7  8]
 [ 1  7]]
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


3.Доступ к строкам и столбцам массива

In [ ]:
print(x2)
print(x2[:, 0]) # первый столбец массива x2
print(x2[0, :]) # первая строка массива x2
print(x2[0]) # в случае вывода строки можно написать проще

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[12  7  1]
[12  5  2  4]
[12  5  2  4]


4.Подмассивы, предназначенные только для чтения представления

In [ ]:
# Срезы массивов возвращают представления (views), а не копии (copies) данных массивов. Это отличие от срезов списков Python,
# где возвращаются копии.
print(x2)
x2_sub = x2[:2, :2]
print(x2_sub)

# Теперь, если изменим этот массив, то увидим, что исходный массив поменялся:
x2_sub[0,0] = 55
print(x2_sub)
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99  5]
 [ 7  6]]
[[55  5]
 [ 7  6]]
[[55  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


5.Создание копий массивов

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

# Если теперь поменяем массив, то исходный останется неизменным:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[55  5]
 [ 7  6]]
[[42  5]
 [ 7  6]]
[[55  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


**Изменение формы массивов**

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) # преобразование в вектор-строку с помощью reshape
# x[np.newaxis, :] # преобразование в вектор-строку с помощью newaxis

# x.reshape((3, 1)) # преобразование в вектор-столбец с помощью reshape
# x[:, np.newaxis] # преобразование в вектор-столбец с помощью newaxis

array([[1, 2, 3]])

In [ ]:
x = np.array([(1, 2, 3), (4, 5, 6)])
print(x)
print(np.resize(x, (2, 2))) # вырезает часть матрицы
print(np.resize(x, (1,3)))
print(np.resize(x, (3,5)))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]]
[[1 2 3]]
[[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 1 2 3]]


**Слияние и разбиение массивов**

1.Слияние массивов

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))

z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]


In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([grid, grid])) # слияние по первой оси координат
print(np.concatenate([grid, grid], axis=1)) # слияние по второй оси координат

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
print(np.vstack([x, grid]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [ ]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

2.Разбиение массивов

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
print(grid)

upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Выполнение вычислений над массивами: универсальные функции

**Введение в универсальные функции**

На языке Python для обхода массива значений приходится в цикле каждый раз вызывать функцию и делать одни и те же вычисления. Это невыгодно каждый раз вычислять одну и ту же функцию, поэтому в NumPy ввели универсальные функции (ufuncs), которые осуществляют компилируемые процедуры со статической типизацией (векторизованная операция). Векторизованный подход спроектирован так, чтобы переносить цикл в скомпилированный слой, лежащий в основе библиотеки NumPy, что обеспечивает высокую производительность.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.sqrt(arr)
np.sin(arr)
np.cos(arr)
np.log(arr)
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

# Агрегирование: минимум, максимум и все, что посередине

Очень часто при работе с большими объемами данных первый шаг заключается в вычислении сводных статистических показателей по этим данным: среднее значение, стандартное отклонение, сумма, произведение, медиана, минимум и максимум, квантили и т.д.

**Сумма значений из массива**

In [ ]:
import numpy as np
L = np.random.random(100)
print(sum(L)) # средствами Python
print(np.sum(L)) # средствами NumPy

54.60397054740112
54.60397054740111


In [ ]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 5: 86.7 ms per loop
1000 loops, best of 5: 368 µs per loop


**Минимум и максимум**

In [ ]:
min(big_array), max(big_array) # Python

(7.488882143302789e-07, 0.9999987530563781)

In [ ]:
np.min(big_array), np.max(big_array) # NumPy

(7.488882143302789e-07, 0.9999987530563781)

In [ ]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 5: 59.6 ms per loop
1000 loops, best of 5: 415 µs per loop


In [ ]:
print(big_array.min(), big_array.max(), big_array.sum())

7.488882143302789e-07 0.9999987530563781 500314.54631960345


# Операции над массивами. Транслирование

Еще один способ применения операций векторизации - транслирование.

In [ ]:
# Для массивов одного размера бинарные операции выполняются поэлементно.
import numpy as np

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [ ]:
# Транслирование дает выполнять бинарные операции над массивами различных размеров:
a + 5

array([5, 6, 7])

In [ ]:
# Операция сложения одномерного и двумерного массивов:
m = np.ones((3, 3))
print(m)
print(m + a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
# Более сложный случай - транслирование обоих массивов:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

a + b

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

**Правила транслирования**

Правило 1. Если размерность двух массивов отличается, форма массива с мешьшей размерностью дополняется единицами с ведущей (левой) стороны.

Правило 2. Если форма двух массивов не совпадает в каком-то измерении, массив с формой, равной 1в данном измерении, растягивается
вплоть до соответствия форме другого массива.

Правило 3. Если в каком-то измерении размеры массивов различаются и ни один не равен 1, генерируется ошибка.

In [ ]:
# Пример 1.
M =np.ones((2, 3))
a = np.arange(3)
print(M)
print(a)

print(M.shape, a.shape)

M + a

In [ ]:
# Пример 2.
a = np.arange(3).reshape(3, 1)
b = np.arange(3)
print(a)
print(b)

print(a.shape, b.shape)
a + b

[[0]
 [1]
 [2]]
[0 1 2]
(3, 1) (3,)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
# Пример 3.
M = np.ones((3, 2))
a = np.arange(3)
print(M)
print(a)

print(M.shape, a.shape)

# M + a - выдаст ошибку
M + a[:, np.newaxis]


[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]
(3, 2) (3,)


array([[1., 1.],
       [2., 2.],
       [3., 3.]])

# Сравнения, маски и булева логика

Маскирование удобно для извлечения, модификации, подсчета или других манипуляций со значениями в массиве по какому-либо критерию.

**Операторы сравнения как универсальные функции**

In [ ]:
# Операторы сравнения в NumPy реализованы как универсальные функции
x = np.array([1, 2, 3, 4, 5])
print(x < 3)
print(x > 3)
print(x <= 3)
print(x >= 3)
print(x != 3)
print(x == 3)

In [ ]:
# Так же и с массивами:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
print(x)
print(x < 6)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


**Работа с булевыми массивами**

Подсчет количества элементов

In [ ]:
count = np.count_nonzero(x < 6) # сколько значенией х < 6 в массиве?
print(count)
count = np.sum(x < 6)
print(count)
count = np.sum(x < 6, axis=1) # сколько значенией х < 6 содержится в каждой строке? как видно sum имеет преимущество
print(count)

In [ ]:
count = np.any(x > 8) # имеются ли значения больше 8?
print(count)
count = np.any(x < 0)
print(count)
count = np.all(x < 10) # все ли значения меньше 10?
print(count)
count = np.all(x == 6)
print(count)
count = np.all(x < 8, axis=1) # все ли значения в каждой строке меньше 8?
print(count)

Булевы операторы

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
print(x)
count = np.sum((x > 2) & (x < 6)) # можно использовать побитовые операторы для более сложных запросов
print(count)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
6


**Булевы массивы как маски**

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
print(x)
print(x < 5)
# чтобы выбрать нужные значения из массива, нужно проиндексировать исходный массив по этому булеву массиву
# эта операция называется маскирование
print(x[x < 5])

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
[0 3 3 3 2 4]


# "Прихотливая" индексация

Прихотливая индексация похожа на простую индексацию, но вместо скалярных значений передаются массивы индексов с целью одновременного доступа к нескольким элементам.

In [ ]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

ind = [3, 7, 4]
print(x[ind])

ind = np.array([[3, 7],
                [4, 5]])

print(x[ind])

[51 92 14 71 60 20 82 86 74 74]
[71 86 60]
[[71 86]
 [60 20]]


In [ ]:
# В случае многомерных массивов:
x = np.arange(12).reshape((3,4))
print(x)

row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(x[row, col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  5 11]


**Комбинированная индексация**

In [ ]:
x = np.arange(12).reshape((3,4))
print(x)

print(x[2, [2, 0, 1]])
print(x[1:, [2, 0, 1]])

mask = np.array([1, 0, 1, 0], dtype=bool)
print(x[row[:, np.newaxis], mask])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[10  8  9]
[[ 6  4  5]
 [10  8  9]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


**Изменение массивов с помощью прихотливой индексации**

In [ ]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [ ]:
# Однако если индекс повторяется, то:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

i = [2, 3, 3, 4, 4, 4]
x[i] += 1
print(x)

# а если надо, чтоб инкрементировалось несколько раз:
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


# Сортировка массивов

**Быстрая сортировка**

In [ ]:
# Сортировка входного массива без его изменения
x = np.array([2, 1, 4, 3, 5])
print(np.sort(x))

# Сортировка с изменением имеющегося массива
x.sort()
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
# Сортирует и возвращает индексы отсортированных элементов
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

x[i] # используя i посредством прихотливой индексации можно построить отсортированный массив:

Сортировка по строкам и столбцам

In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))
print(x)

# сортируем все столбцы
print(np.sort(x, axis=0))

# сортируем все строки
print(np.sort(x, axis=1))

**Частичные сортировки: секционирование**

In [ ]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
print(x)
print(np.partition(x, 3)) # первые три значения в итоговом массиве - три наименьших значения, а на остальных - все прочие значения

y = rand.randint(0, 10, (4, 6))
print(y)
print(np.partition(y, 2, axis=1)) # секционирование по произвольной оси многомерного массива, в результате получаем массив,у которого на первых двух позициях каждой строки наименьшие значения

[7 2 3 1 6 5 4]
[2 1 3 4 6 5 7]
[[9 9 2 6 0 3]
 [3 4 6 6 3 6]
 [2 5 1 9 8 4]
 [5 3 9 6 8 6]]
[[0 2 3 6 9 9]
 [3 3 4 6 6 6]
 [1 2 4 9 8 5]
 [3 5 6 9 8 6]]


# Структурированные данные: структурированные массивы и массивы записей

In [ ]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

print(data['name'])
print(data[0])
print(data[-1]['name'])

print(data[data['age'] < 30]['name'])

**Создание структурированных массивов**

In [ ]:
# с использованием словаря
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

np.dtype({'names':('name', 'age', 'weight'),
          'formats': ((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [ ]:
# в виде списка кортежей
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [ ]:
# если названия типов не важны, то
np.dtype('S10, i4, f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

# Полезные операции

## Векторизация

Задача. Требуется применить некотору функцию к элементам массива.

In [ ]:
import numpy as np

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
add_100 = lambda i: i + 100

In [ ]:
vectorized_add_100 = np.vectorize(add_100)

In [ ]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

Эту же задачу легче сделать с помощью трансляции

In [ ]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])