# Тема 1.1. Библиотека Numpy

In [1]:
import numpy as np

## Самостоятельная работа №1.1 (часть 1)

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
df = np.loadtxt('../Семинар 1/data/minutes_n_ingredients.csv', delimiter=',', dtype=str)
columns_names = df[0]
df = np.array(df[1:], dtype=np.int16)
df[:5]

array([[-3828,    60,    16],
       [23891,    25,     7],
       [29210,    10,     6],
       [ 2124,     5,     6],
       [26839,    60,    14]], dtype=int16)

In [3]:
columns_names

array(['id', 'minutes', 'n_ingredients'], dtype='<U13')

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [4]:
print(df.mean(axis=0)[1:])
print(df.min(axis=0)[1:])
print(np.median(df, axis=0)[1:])

[90.12041  9.05528]
[-30966      1]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [5]:
q = np.quantile(df[:, 1], 0.75)
df[df[:, 1] > q] = q
df

array([[ -3828,     60,     16],
       [ 23891,     25,      7],
       [ 29210,     10,      6],
       ...,
       [-25856,     65,     15],
       [-22301,      5,      4],
       [    65,     65,     65]], dtype=int16)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [6]:
print(df[df[:, 1] == 0].size)
df[df[:, 1] == 0] = 1

1437


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [7]:
np.unique(df[:, 0]).size

46542

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [8]:
unique, count = np.unique(df[:, 2], return_counts=True)
{v: k for k, v in zip(unique, count)}

{491: 1,
 792: 2,
 2544: 3,
 4781: 4,
 6692: 5,
 7655: 6,
 8449: 7,
 8477: 8,
 8107: 9,
 7022: 10,
 5809: 11,
 4568: 12,
 3352: 13,
 2317: 14,
 1569: 15,
 1055: 16,
 677: 17,
 413: 18,
 277: 19,
 175: 20,
 88: 21,
 65: 22,
 33: 23,
 27: 24,
 26: 25,
 7: 29,
 5: 28,
 4: 30,
 1: 34,
 24509: 65}

## Самостоятельная работа №1.1 (часть 2)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [9]:
df[df[:, 2] <= 5]

array([[-12155,     15,      5],
       [  7526,      5,      3],
       [ 25623,      6,      4],
       ...,
       [-13448,     60,      5],
       [ -2261,     15,      4],
       [-22301,      5,      4]], dtype=int16)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [10]:
(df[:, 2] / df[:, 1]).max()

23.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [16]:
df[df[:, 1].argsort()][-100:, 2].mean()

61.12

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [23]:
index = np.random.choice(df.shape[0], 10)
df[index, :]

array([[-18892,     20,      3],
       [  -762,     45,     11],
       [ 12772,     65,     12],
       [ 12241,     40,     10],
       [    65,     65,     65],
       [ -8695,     15,      8],
       [    65,     65,     65],
       [  3979,     35,      4],
       [ 29049,     50,      9],
       [ 27514,     10,      4]], dtype=int16)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [27]:
df[df[:, 2] < df[:, 2].mean()].shape[0] / df.shape[0]

0.75375

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [38]:
new_ = ((df[:, 1] <= 20) & (df[:, 2] <= 5)).astype(int)

In [41]:
df_new = np.hstack((df, new_.reshape((-1, 1))))
df_new

array([[ -3828,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 29210,     10,      6,      0],
       ...,
       [-25856,     65,     15,      0],
       [-22301,      5,      4,      1],
       [    65,     65,     65,      0]])

13. Выведите процент "простых" рецептов в датасете

In [43]:
df_new[df_new[:, 3] == 1].shape[0] / df_new.shape[0]

0.09962

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.